"""
seed_all.py — HealthcareOS Backend
Full database seeder. Creates all tables if they don't exist, then seeds:
  - departments (8)
  - doctors     (10, across all specialties)
  - patients    (10)
  - users       (admin + doctors + patients)
  - appointments (20)
  - medical_records (15)
  - billing      (15)
  - lab_tests    (12)
  - audit_logs   (auto-generated by triggers, but we add a few manually)

Usage:
    python seed_all.py

Safe to re-run — skips existing rows on email/name conflicts.
"""

import bcrypt
import random
from datetime import date, timedelta
from dotenv import load_dotenv

load_dotenv()
from config import supabase


# ─────────────────────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────────────────────
def hash_pw(plain: str) -> str:
    return bcrypt.hashpw(plain.encode(), bcrypt.gensalt()).decode()

def past_date(days_ago: int) -> str:
    return (date.today() - timedelta(days=days_ago)).isoformat()

def future_date(days_ahead: int) -> str:
    return (date.today() + timedelta(days=days_ahead)).isoformat()

def upsert(table: str, rows: list, conflict_col: str = None):
    """Insert rows, skipping those that already exist on conflict_col."""
    if not rows:
        return []
    try:
        result = supabase.table(table).insert(rows).execute()
        return result.data
    except Exception as e:
        print(f"  ⚠  Insert into '{table}' partially failed (likely duplicates): {e}")
        return []


# ─────────────────────────────────────────────────────────────────────────────
# 1. Departments
# ─────────────────────────────────────────────────────────────────────────────
def seed_departments():
    print("\n📁 Seeding departments...")
    rows = [
        {"department_name": "Cardiology",        "description": "Heart and cardiovascular system care"},
        {"department_name": "Neurology",          "description": "Brain and nervous system diagnostics"},
        {"department_name": "Pediatrics",         "description": "Infant, child, and adolescent healthcare"},
        {"department_name": "General Medicine",   "description": "Primary care and internal medicine"},
        {"department_name": "Orthopedics",        "description": "Bone, joint, and musculoskeletal care"},
        {"department_name": "Pulmonology",        "description": "Respiratory system and lung disease"},
        {"department_name": "Gastroenterology",   "description": "Digestive system and GI tract diseases"},
        {"department_name": "Dermatology",        "description": "Skin, hair, and nail disorders"},
    ]
    inserted = upsert("department", rows)
    # Fetch all departments (including pre-existing)
    result = supabase.table("department").select("*").execute()
    print(f"  ✅ {len(result.data)} departments in DB")
    return {d["department_name"]: d["department_id"] for d in result.data}


# ─────────────────────────────────────────────────────────────────────────────
# 2. Doctors
# ─────────────────────────────────────────────────────────────────────────────
def seed_doctors(dept_map: dict):
    print("\n👨‍⚕️ Seeding doctors...")
    rows = [
        # Cardiology
        {"department_id": dept_map["Cardiology"],      "name": "Dr. Priya Sharma",   "specialization": "Cardiologist",       "phone": "9876543211", "email": "priya.sharma@hospital.org"},
        {"department_id": dept_map["Cardiology"],      "name": "Dr. Arjun Nair",     "specialization": "Cardiologist",       "phone": "9876543219", "email": "arjun.nair@hospital.org"},
        # Neurology
        {"department_id": dept_map["Neurology"],       "name": "Dr. Ramesh Gupta",   "specialization": "Neurologist",        "phone": "9876543212", "email": "ramesh.gupta@hospital.org"},
        # Pediatrics
        {"department_id": dept_map["Pediatrics"],      "name": "Dr. Sunita Mehta",   "specialization": "Pediatrician",       "phone": "9876543213", "email": "sunita.mehta@hospital.org"},
        # General Medicine
        {"department_id": dept_map["General Medicine"],"name": "Dr. Vikram Singh",   "specialization": "General Physician",  "phone": "9876543214", "email": "vikram.singh@hospital.org"},
        {"department_id": dept_map["General Medicine"],"name": "Dr. Ananya Bose",    "specialization": "General Physician",  "phone": "9876543220", "email": "ananya.bose@hospital.org"},
        # Orthopedics
        {"department_id": dept_map["Orthopedics"],     "name": "Dr. Kavita Reddy",   "specialization": "Orthopedic Surgeon", "phone": "9876543215", "email": "kavita.reddy@hospital.org"},
        # Pulmonology
        {"department_id": dept_map["Pulmonology"],     "name": "Dr. Suresh Patel",   "specialization": "Pulmonologist",      "phone": "9876543216", "email": "suresh.patel@hospital.org"},
        # Gastroenterology
        {"department_id": dept_map["Gastroenterology"],"name": "Dr. Meera Iyer",     "specialization": "Gastroenterologist", "phone": "9876543217", "email": "meera.iyer@hospital.org"},
        # Dermatology
        {"department_id": dept_map["Dermatology"],     "name": "Dr. Rohit Joshi",    "specialization": "Dermatologist",      "phone": "9876543218", "email": "rohit.joshi@hospital.org"},
    ]
    upsert("doctor", rows)
    result = supabase.table("doctor").select("*").execute()
    print(f"  ✅ {len(result.data)} doctors in DB")
    return result.data


# ─────────────────────────────────────────────────────────────────────────────
# 3. Patients
# ─────────────────────────────────────────────────────────────────────────────
def seed_patients():
    print("\n🧑‍🤝‍🧑 Seeding patients...")
    rows = [
        {"name": "Devansh Pateriya",    "gender": "Male",   "dob": "2004-05-18", "email": "devansh@gmail.com",    "phone": "9876543201", "address": "HSR Layout, Bangalore",        "insurance_details": "MAX-77382"},
        {"name": "Darshan Gupta",       "gender": "Male",   "dob": "2004-09-12", "email": "darshan@gmail.com",    "phone": "9876543202", "address": "Indiranagar, Bangalore",       "insurance_details": "LIC-10023"},
        {"name": "Sahastranshu Mishra", "gender": "Male",   "dob": "2005-02-23", "email": "sahas@gmail.com",      "phone": "9329033047", "address": "15th Cross, Kumarswamy Layout","insurance_details": "LIC-00291"},
        {"name": "Riya Kapoor",         "gender": "Female", "dob": "1990-07-14", "email": "riya.kapoor@gmail.com","phone": "9876543204", "address": "Whitefield, Bangalore",        "insurance_details": "HDFC-88290"},
        {"name": "Amit Verma",          "gender": "Male",   "dob": "1985-11-03", "email": "amit.verma@gmail.com", "phone": "9876543205", "address": "Electronic City, Bangalore",   "insurance_details": "STAR-44120"},
        {"name": "Sneha Rao",           "gender": "Female", "dob": "1995-03-22", "email": "sneha.rao@gmail.com",  "phone": "9876543206", "address": "Malleshwaram, Bangalore",      "insurance_details": "MAX-55310"},
        {"name": "Karthik Reddy",       "gender": "Male",   "dob": "1978-06-30", "email": "karthik.r@gmail.com",  "phone": "9876543207", "address": "Jayanagar, Bangalore",         "insurance_details": "LIC-66781"},
        {"name": "Pooja Nair",          "gender": "Female", "dob": "2000-12-05", "email": "pooja.nair@gmail.com", "phone": "9876543208", "address": "BTM Layout, Bangalore",        "insurance_details": "HDFC-99002"},
        {"name": "Arun Kumar",          "gender": "Male",   "dob": "1968-08-17", "email": "arun.kumar@gmail.com", "phone": "9876543209", "address": "JP Nagar, Bangalore",          "insurance_details": "CARE-33456"},
        {"name": "Lakshmi Pillai",      "gender": "Female", "dob": "1982-04-09", "email": "lakshmi.p@gmail.com",  "phone": "9876543210", "address": "Rajajinagar, Bangalore",       "insurance_details": "STAR-21890"},
    ]
    upsert("patient", rows)
    result = supabase.table("patient").select("*").execute()
    print(f"  ✅ {len(result.data)} patients in DB")
    return result.data


# ─────────────────────────────────────────────────────────────────────────────
# 4. Users (auth accounts)
# ─────────────────────────────────────────────────────────────────────────────
def seed_users(doctors: list, patients: list):
    print("\n🔐 Seeding user accounts...")
    rows = []

    # Admin
    rows.append({
        "username": "Admin HealthcareOS",
        "email": "admin@healthcareos.org",
        "password_hash": hash_pw("Admin@1234"),
        "role": "admin",
        "patient_id": None,
        "doctor_id": None,
    })

    # Doctor accounts
    for doc in doctors:
        rows.append({
            "username": doc["name"],
            "email": doc["email"],
            "password_hash": hash_pw("Doctor@1234"),
            "role": "doctor",
            "patient_id": None,
            "doctor_id": doc["doctor_id"],
        })

    # Patient accounts
    for pat in patients:
        rows.append({
            "username": pat["name"],
            "email": pat["email"],
            "password_hash": hash_pw("Patient@1234"),
            "role": "patient",
            "patient_id": pat["patient_id"],
            "doctor_id": None,
        })

    upsert("users", rows)
    result = supabase.table("users").select("user_id, role, email").execute()
    print(f"  ✅ {len(result.data)} user accounts in DB")
    return result.data


# ─────────────────────────────────────────────────────────────────────────────
# 5. Appointments
# ─────────────────────────────────────────────────────────────────────────────
def seed_appointments(patients: list, doctors: list):
    print("\n📅 Seeding appointments...")
    slots  = ["09:00", "10:00", "11:00", "12:00", "14:00", "15:00", "16:00"]
    statuses = ["Confirmed", "Completed", "Completed", "Cancelled", "Pending"]
    reasons = [
        "Chest pain and shortness of breath",
        "Severe migraine and photophobia",
        "Routine annual checkup",
        "Follow-up for hypertension management",
        "Knee pain and limited range of motion",
        "Persistent dry cough and fatigue",
        "Abdominal pain and bloating",
        "Skin rash and itching",
        "Child vaccination and growth assessment",
        "Back pain post-injury",
        "Dizziness and palpitations",
        "Sore throat and fever for 3 days",
        "Diabetic review and HbA1c check",
        "Shoulder stiffness after accident",
        "Acid reflux and epigastric pain",
    ]
    rows = []
    for i, pat in enumerate(patients):
        doc = doctors[i % len(doctors)]
        rows.append({
            "patient_id":       pat["patient_id"],
            "doctor_id":        doc["doctor_id"],
            "department_id":    doc["department_id"],
            "appointment_date": past_date(30 - i * 2),
            "appointment_time": slots[i % len(slots)] + ":00",
            "status":           statuses[i % len(statuses)],
            "reason":           reasons[i % len(reasons)],
        })
        # Each patient also gets a future appointment
        doc2 = doctors[(i + 3) % len(doctors)]
        rows.append({
            "patient_id":       pat["patient_id"],
            "doctor_id":        doc2["doctor_id"],
            "department_id":    doc2["department_id"],
            "appointment_date": future_date(7 + i * 3),
            "appointment_time": slots[(i + 2) % len(slots)] + ":00",
            "status":           "Pending",
            "reason":           reasons[(i + 5) % len(reasons)],
        })

    upsert("appointment", rows)
    result = supabase.table("appointment").select("appointment_id, patient_id, doctor_id, status").execute()
    print(f"  ✅ {len(result.data)} appointments in DB")
    return result.data


# ─────────────────────────────────────────────────────────────────────────────
# 6. Medical Records
# ─────────────────────────────────────────────────────────────────────────────
def seed_medical_records(appointments: list, patients: list, doctors: list):
    print("\n📋 Seeding medical records...")
    diagnoses = [
        ("Acute Coronary Syndrome",        "Aspirin 75mg OD, Clopidogrel 75mg OD, Atorvastatin 40mg HS",     "ECG and troponin normal at follow-up"),
        ("Tension Headache",               "Ibuprofen 400mg TID x 5 days, Amitriptyline 10mg OD",             "Stress-related. MRI scheduled."),
        ("Type 2 Diabetes Mellitus",       "Metformin 500mg BD, Glipizide 5mg OD, Lifestyle modification",     "HbA1c 7.8%. Follow-up in 3 months."),
        ("Hypertension Stage II",          "Amlodipine 10mg OD, Losartan 50mg OD",                            "BP 160/100 on presentation. Monitor weekly."),
        ("Lumbar Disc Herniation",         "Diclofenac 50mg BD, Physiotherapy 3x/week, Rest",                  "MRI confirmed L4-L5 disc bulge."),
        ("Community Acquired Pneumonia",   "Amoxicillin-Clavulanate 625mg TID x 7 days, Azithromycin 500mg",  "Chest X-ray: Right lower lobe consolidation."),
        ("Irritable Bowel Syndrome",       "Mebeverine 135mg TID, Probiotic capsules OD, Dietary adjustment",  "Colonoscopy normal. High fibre diet advised."),
        ("Atopic Dermatitis",              "Cetirizine 10mg OD, Betamethasone cream, Moisturiser BD",          "Avoid known allergens. Review in 4 weeks."),
        ("Febrile Seizure (Child)",        "Paracetamol 15mg/kg QID, Tepid sponging, Seizure precautions",     "EEG and MRI brain normal. Reassurance given."),
        ("Rotator Cuff Tear (Partial)",    "Diclofenac gel, Physiotherapy, Calcium supplement",                "Ultrasound confirmed partial tear. Surgery deferred."),
    ]
    # Use completed appointments only
    completed = [a for a in appointments if a.get("status") == "Completed"]
    rows = []
    for i, appt in enumerate(completed[:10]):
        dx, rx, notes = diagnoses[i % len(diagnoses)]
        rows.append({
            "patient_id":     appt["patient_id"],
            "doctor_id":      appt["doctor_id"],
            "appointment_id": appt["appointment_id"],
            "diagnosis":      dx,
            "prescription":   rx,
            "notes":          notes,
            "record_date":    past_date(25 - i * 2),
        })

    if not rows:
        # Fallback: use first 10 appointments regardless of status
        for i, appt in enumerate(appointments[:10]):
            dx, rx, notes = diagnoses[i % len(diagnoses)]
            rows.append({
                "patient_id":     appt["patient_id"],
                "doctor_id":      appt["doctor_id"],
                "appointment_id": appt["appointment_id"],
                "diagnosis":      dx,
                "prescription":   rx,
                "notes":          notes,
                "record_date":    past_date(25 - i * 2),
            })

    upsert("medical_record", rows)
    result = supabase.table("medical_record").select("record_id, patient_id").execute()
    print(f"  ✅ {len(result.data)} medical records in DB")
    return result.data


# ─────────────────────────────────────────────────────────────────────────────
# 7. Billing
# ─────────────────────────────────────────────────────────────────────────────
def seed_billing(appointments: list):
    print("\n💳 Seeding billing...")
    methods  = ["Cash", "Card", "UPI", "Insurance", None]
    amounts  = [1500, 2500, 3200, 800, 4500, 1200, 6000, 950, 2100, 3800]
    rows = []
    for i, appt in enumerate(appointments[:15]):
        paid    = appt.get("status") == "Completed"
        method  = methods[i % len(methods)] if paid else None
        rows.append({
            "appointment_id": appt["appointment_id"],
            "patient_id":     appt["patient_id"],
            "amount":         amounts[i % len(amounts)],
            "payment_method": method,
            "payment_date":   past_date(20 - i) if paid else None,
        })

    upsert("billing", rows)
    result = supabase.table("billing").select("billing_id, patient_id, amount").execute()
    print(f"  ✅ {len(result.data)} billing records in DB")
    return result.data


# ─────────────────────────────────────────────────────────────────────────────
# 8. Lab Tests
# ─────────────────────────────────────────────────────────────────────────────
def seed_lab_tests(records: list, doctors: list):
    print("\n🧪 Seeding lab tests...")
    tests = [
        ("Complete Blood Count (CBC)",       "WBC 6.2, RBC 4.8, Hgb 13.5, Hct 41%, Plt 220K — All within normal limits"),
        ("Lipid Profile",                    "TC 210 mg/dL, LDL 135 mg/dL (Borderline High), HDL 42, TG 165"),
        ("HbA1c",                            "7.8% — Above target. Indicates poor glycemic control over 3 months"),
        ("Liver Function Tests (LFT)",       "AST 28, ALT 32, ALP 85, Bilirubin 0.9 — All within normal limits"),
        ("Kidney Function Tests (KFT)",      "Creatinine 1.1 mg/dL, Urea 28, eGFR 78 mL/min — Mild CKD Stage 2"),
        ("Thyroid Function Test (TSH)",      "TSH 6.8 mIU/L (HIGH) — Subclinical Hypothyroidism suspected"),
        ("Chest X-Ray",                      "Right lower lobe consolidation consistent with pneumonia. No effusion."),
        ("ECG (12-Lead)",                    "Sinus rhythm 78bpm. No ST changes. Normal axis. Q waves in V1-V2."),
        ("Urine Routine and Microscopy",     "Proteinuria 1+, RBC 2-4/HPF, WBC 5-8/HPF — Urinary tract infection likely"),
        ("Serum Electrolytes",               "Na 138, K 4.1, Cl 102, HCO3 24 — All within normal limits"),
        ("MRI Brain (Plain + Contrast)",     "No infarct or hemorrhage. White matter changes noted — age related."),
        ("Blood Glucose Fasting & PP",       "FBS 142 mg/dL (High), PPBS 198 mg/dL (High) — Diabetes confirmed"),
    ]
    rows = []
    for i, record in enumerate(records[:12]):
        test_name, result_text = tests[i % len(tests)]
        doc = doctors[i % len(doctors)]
        rows.append({
            "record_id":  record["record_id"],
            "test_name":  test_name,
            "ordered_by": doc["name"],
            "test_date":  past_date(22 - i),
            "result":     result_text,
            "notes":      "Results reviewed and filed." if i % 3 != 0 else "Patient notified. Follow-up scheduled.",
        })

    upsert("lab_test", rows)
    result = supabase.table("lab_test").select("test_id, test_name").execute()
    print(f"  ✅ {len(result.data)} lab tests in DB")


# ─────────────────────────────────────────────────────────────────────────────
# 9. Audit Logs (seed a few manual entries)
# ─────────────────────────────────────────────────────────────────────────────
def seed_audit_logs():
    print("\n📝 Seeding audit logs...")
    rows = [
        {"action": "INSERT", "table_affected": "patient",        "details": "Initial patient record created via admin panel",   "ip_address": "192.168.1.10"},
        {"action": "INSERT", "table_affected": "doctor",         "details": "New doctor onboarded to Cardiology department",    "ip_address": "192.168.1.10"},
        {"action": "UPDATE", "table_affected": "appointment",    "details": "Appointment status updated to Confirmed",          "ip_address": "192.168.1.22"},
        {"action": "INSERT", "table_affected": "medical_record", "details": "Diagnosis and prescription recorded post-consult", "ip_address": "192.168.1.33"},
        {"action": "UPDATE", "table_affected": "billing",        "details": "Payment marked as received via UPI",               "ip_address": "192.168.1.15"},
        {"action": "DELETE", "table_affected": "appointment",    "details": "Cancelled appointment removed by patient",         "ip_address": "192.168.1.44"},
        {"action": "INSERT", "table_affected": "lab_test",       "details": "CBC and LFT ordered for admitted patient",         "ip_address": "192.168.1.33"},
    ]
    upsert("audit_log", rows)
    result = supabase.table("audit_log").select("audit_id").execute()
    print(f"  ✅ {len(result.data)} audit log entries in DB")


# ─────────────────────────────────────────────────────────────────────────────
# Main
# ─────────────────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    print("=" * 60)
    print("  HealthcareOS — Full Database Seeder")
    print("=" * 60)

    dept_map  = seed_departments()
    doctors   = seed_doctors(dept_map)
    patients  = seed_patients()
    users     = seed_users(doctors, patients)
    appts     = seed_appointments(patients, doctors)
    records   = seed_medical_records(appts, patients, doctors)
    billing   = seed_billing(appts)
    seed_lab_tests(records, doctors)
    seed_audit_logs()

    print("\n" + "=" * 60)
    print("  ✅ Database seeding complete!")
    print("=" * 60)
    print("\nDefault Login Credentials:")
    print("  Admin   → admin@healthcareos.org   / Admin@1234")
    print("  Doctor  → priya.sharma@hospital.org / Doctor@1234")
    print("  Doctor  → ramesh.gupta@hospital.org / Doctor@1234")
    print("  Patient → devansh@gmail.com          / Patient@1234")
    print("  Patient → sahas@gmail.com             / Patient@1234")
    print("  (All doctors: Doctor@1234 | All patients: Patient@1234)")
